# Generated by Django 2.2.2 on 2019-06-19 07:43

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
